---
- hosts: all
  become: yes
  tasks:



  - name: setting selinux to permissive
    selinux:
      policy: targeted
      state: permissive

  - name: dynamic fetching of app
    copy:
      src: httpd.conf
      dest: /etc/httpd/conf/httpd.conf

  - name: starting httpd
    service:
      name: httpd

        # - name: Unconditionally reboot the machine with all defaults
        # ansible.builtin.reboot:
